import { Header } from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='ja'>
      <body className='bg-base-300 min-h-screen overflow-hidden w-full'>
        <Header />
        {children}
      </body>
    </html>
  )
}
